version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '9090:80'
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./exchange_api
    environment:
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 9093:9093
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./exchange_client
    environment:
      - API_HOST=api
      - API_PORT=9093
    volumes:
      - /app/node_modules
      - ./exchange_client:/app